=== riftgarret/ludum/json/schemas/encounters-schema.json
{
  "$schema": "http://json-schema.org/draft-04/schema",
  "title": "Schema for defining encounters",
  "definitions": {
    "coordinate": {
      "type": "string",
      "pattern": "\\d+,\\d+"
    }
  },
  "type": "array",
  "items": {
    "type": "object",
    "required": [
      "dataId",
      "enemyGridSize",
      "playerGridSize",
      "enemies"
    ],
    "properties": {
      "dataId": { "$ref": "global-defs.json#/definitions/dataId" },
      "enemyGridSize": {
        "description": "Enemy grid dimensions",
        "allOf": [ { "$ref": "#/definitions/coordinate" } ]
      },
      "playerGridSize": {
        "description": "Player grid dimensions",
        "allOf": [ { "$ref": "#/definitions/coordinate" } ]
      },
      "enemies": {
        "description": "Enemy units",
        "type": "array",
        "items": {
          "type": "object",
          "required": [
            "characterId",
            "aibehaviorid",
            "position"
          ],
          "properties": {
            "characterId": {
              "description": "Character resource identifier",
              "allOf": [ { "$ref": "global-defs.json#/definitions/dataId" } ]
            },
            "aibehaviorid": {
              "description": "AI behavior resource identifier",
              "allOf": [ { "$ref": "global-defs.json#/definitions/dataId" } ]
            },
            "position": {
              "description": "Unit grid position",
              "allOf": [ { "$ref": "#/definitions/coordinate" } ]
            }
          }
        }
      }
    }
  }
}

=== riftgarret/ludum/Ludum/Assets/Resources/Configs/Sandbox/encounters.json
[
  {
    "dataId": "goblin_party",
    "enemyGridSize": "3,3",
    "playerGridSize": "3,3",
    "enemies": [
      {
        "characterId": "goblin",
        "aibehaviorid": "goblin_warrior",
        "position": "1,0"
      },
      {
        "characterId": "goblin",
        "aibehaviorid": "goblin_priest",
        "position": "1,1"
      },
      {
        "characterId": "goblin",
        "aibehaviorid": "goblin_warrior",
        "position": "0,0"
      }
    ]
  }
]
